# 应用名称
spring:
  application:
    name: Web-Backend-Server
    version: 1.0.0-SNAPSHOT

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: Alc@tel12

  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      # DB will be drop&create each time, initial data will be seeded by domain.repository.seeders.DataSeeder
      ddl-auto: create-drop

  # Html模板
  thymeleaf:
    cache: false  # 开发时关闭缓存，否则无法看到实时页面
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

# 应用服务 WEB访问端口
server:
  port: 8080
  error:
    include-message: always

# 日志服务
logging:
  file:
    name: ../logs/web-backend-springboot.log
  level:
    org.springframework.web: DEBUG