GET http://localhost:8080
###
GET http://localhost:8080/api
###
GET http://localhost:8080/api/products
###
GET http://localhost:8080/api/products/backend
###
GET http://localhost:8080/api/products/backend?sort=desc
###
GET http://localhost:8080/api/products/backend?page=4
###
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "id": 4,
  "title": "Title New",
  "description": "Description New",
  "image": "http://focus617.com/200/200?1234",
  "price": 17.096355532475926
}
###
GET http://localhost:8080/api/products/4
###
PATCH http://localhost:8080/api/products
Content-Type: application/json

{
  "id": 4,
  "title": "Title Changed",
  "description": "Description Changed",
  "image": "http://focus617.com/200/200?9876",
  "price": 1.2345678
}
###
DELETE http://localhost:8080/api/products/4